/**
 * This file was generated by the JPA Modeler
 */
package com.desktopclient.entidades;

import java.io.Serializable;
import java.util.Objects;

import javax.xml.bind.annotation.*;

/**
 * @author Windows XP
 */
//@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
//@NamedQueries({
//    @NamedQuery(name = "Rol.findAll", query = "Select e from Rol e"),
//    @NamedQuery(name = "Rol.findByTipo", query = "Select r from Rol r where r.tipo=:tipo")})
public class Rol implements Serializable {

  
    private Long id;

    private String tipo;

    public Rol(Long id, String tipo) {
        this.id = id;
        this.tipo = tipo;
    }

    public Rol() {
    }

    public Rol(String tipo) {
        this.tipo = tipo;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 53 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Rol other = (Rol) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }
    
    

}
