/**
 * This file was generated by the JPA Modeler
 */
package com.desktopclient.entidades;

import java.io.Serializable;
import java.util.List;

/**
 * @author Windows XP
 */
public class Usuario implements Serializable {

    private String cedula;

    private String nombre;

    private String apellido;

    private String email;

    private String password;

    private List<Estudiante_Examen> calificacionesExamenes;

    private List<Estudiante_Curso> calificacionesCursos;

    private List<Rol> roles;

    private List<Carrera> carreras;

    private List<Examen> inscripcionesExamenes;

    private List<Curso> cursoes;

    public Usuario(String cedula, String nombre, String apellido, String email, String password) {
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.password = password;
    }

    public Usuario() {
    }

    public String getCedula() {
        return this.cedula;
    }

    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<Estudiante_Examen> getCalificacionesExamenes() {
        return this.calificacionesExamenes;
    }

    public void setCalificacionesExamenes(List<Estudiante_Examen> calificacionesExamenes) {
        this.calificacionesExamenes = calificacionesExamenes;
    }

    public List<Estudiante_Curso> getCalificacionesCursos() {
        return this.calificacionesCursos;
    }

    public void setCalificacionesCursos(List<Estudiante_Curso> calificacionesCursos) {
        this.calificacionesCursos = calificacionesCursos;
    }

    public List<Rol> getRoles() {
        return this.roles;
    }

    public void setRoles(List<Rol> roles) {
        this.roles = roles;
    }

    public List<Carrera> getCarreras() {
        return this.carreras;
    }

    public void setCarreras(List<Carrera> carreras) {
        this.carreras = carreras;
    }

    public List<Examen> getInscripcionesExamenes() {
        return this.inscripcionesExamenes;
    }

    public void setInscripcionesExamenes(List<Examen> inscripcionesExamenes) {
        this.inscripcionesExamenes = inscripcionesExamenes;
    }

    public List<Curso> getCursoes() {
        return this.cursoes;
    }

    public void setCursoes(List<Curso> cursoes) {
        this.cursoes = cursoes;
    }

}
