/**
 * This file was generated by the JPA Modeler
 */
package Entidades;

import java.io.Serializable;
import java.util.List;

/**
 * @author Windows XP
 */
public class Asignatura implements Serializable {

    private Long codigo;


    private String nombre;


    private List<Asignatura_Carrera> asignatura_Carreras;


    private List<Carrera> carreras;

    public Asignatura(Long codigo, String nombre) {
        this.codigo = codigo;
        this.nombre = nombre;
    }

    public Asignatura() {
    }

    public Long getCodigo() {
        return this.codigo;
    }

    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public List<Asignatura_Carrera> getAsignatura_Carreras() {
        return this.asignatura_Carreras;
    }

    public void setAsignatura_Carreras(List<Asignatura_Carrera> asignatura_Carreras) {
        this.asignatura_Carreras = asignatura_Carreras;
    }

    public List<Carrera> getCarreras() {
        return this.carreras;
    }

    public void setCarreras(List<Carrera> carreras) {
        this.carreras = carreras;
    }

}
