/**
 * This file was generated by the JPA Modeler
 */
package Entidades;

import java.io.Serializable;

/**
 * @author Windows XP
 */
public class Estudiante_Examen implements Serializable {

    private Long id;

    private Long calificacion;

    private Examen examen;

    private Usuario usuario;

    public Estudiante_Examen(Long id, Long calificacion) {
        this.id = id;
        this.calificacion = calificacion;
    }

    public Estudiante_Examen() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCalificacion() {
        return this.calificacion;
    }

    public void setCalificacion(Long calificacion) {
        this.calificacion = calificacion;
    }

    public Examen getExamen() {
        return this.examen;
    }

    public void setExamen(Examen examen) {
        this.examen = examen;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

}
