/**
 * This file was generated by the JPA Modeler
 */
package Entidades;

import java.io.Serializable;

/**
 * @author Windows XP
 */
public class Horario implements Serializable {

    private Long id;

    private int horaInicio;

    private int horaFin;

    public Horario(Long id, int horaInicio, int horaFin) {
        this.id = id;
        this.horaInicio = horaInicio;
        this.horaFin = horaFin;
    }

    public Horario() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getHoraInicio() {
        return this.horaInicio;
    }

    public void setHoraInicio(int horaInicio) {
        this.horaInicio = horaInicio;
    }

    public int getHoraFin() {
        return this.horaFin;
    }

    public void setHoraFin(int horaFin) {
        this.horaFin = horaFin;
    }

}
